/**
 * Comprehensive starter catalogue of Indian-market medicine brands, as used in
 * everyday Indian practice (no list can literally contain all ~40,000 market
 * brands — this covers virtually all commonly prescribed ones; anything else
 * slots in via Pharmacy → Import catalogue, CSV or single add).
 *
 * Forms must use canonical MED_CATEGORIES casing. Many names appear in
 * multiple forms or strengths on purpose — that is exactly the on-screen
 * "Syrup or Drops or Injection?" chooser the doctor gets.
 */
export interface IndianDrugSeed {
  name: string;
  form: string;
  strength: string;
}

export const INDIAN_DRUGS: readonly IndianDrugSeed[] = [
  /* ---- fever / pain / inflammation ---- */
  { name: "Dolo 650", form: "Tablet", strength: "650 mg" },
  { name: "Crocin", form: "Tablet", strength: "500 mg" },
  { name: "Calpol", form: "Tablet", strength: "500 mg" },
  { name: "Calpol", form: "Syrup", strength: "250 mg/5 ml" },
  { name: "Calpol", form: "Drops", strength: "100 mg/ml" },
  { name: "Meftal", form: "Tablet", strength: "500 mg" },
  { name: "Meftal", form: "Suspension", strength: "100 mg/5 ml" },
  { name: "Meftal-Spas", form: "Tablet", strength: "dicyclomine 10 mg + 250 mg" },
  { name: "Brufen", form: "Tablet", strength: "400 mg" },
  { name: "Brufen", form: "Tablet", strength: "600 mg" },
  { name: "Ibugesic Plus", form: "Syrup", strength: "100 mg + 162.5 mg/5 ml" },
  { name: "Combiflam", form: "Tablet", strength: "400 mg + 325 mg" },
  { name: "Ultracet", form: "Tablet", strength: "37.5 mg + 325 mg" },
  { name: "Zerodol", form: "Tablet", strength: "100 mg" },
  { name: "Zerodol-P", form: "Tablet", strength: "100 mg + 325 mg" },
  { name: "Zerodol-MR", form: "Capsule", strength: "100 mg + 8 mg + 325 mg" },
  { name: "Diclomol", form: "Tablet", strength: "50 mg" },
  { name: "Voveran", form: "Tablet", strength: "50 mg" },
  { name: "Voveran AQ", form: "Injection", strength: "75 mg/3 ml" },
  { name: "Nimulid", form: "Tablet", strength: "100 mg" },
  { name: "Nimulid", form: "Suspension", strength: "100 mg" },
  { name: "Volini", form: "Ointment / Cream", strength: "1.16% gel" },
  { name: "Iodex", form: "Ointment / Cream", strength: "balm" },
  { name: "Moov", form: "Ointment / Cream", strength: "pain relief" },
  { name: "Zandu Balm", form: "Ointment / Cream", strength: "8 ml" },
  { name: "Zerodol-SP", form: "Tablet", strength: "100 + 325 + 15 mg" },
  { name: "Signoflam", form: "Tablet", strength: "100 + 325 + 15 mg" },
  { name: "Flexon", form: "Tablet", strength: "400 mg + 325 mg" },
  { name: "Chymoral Forte", form: "Tablet", strength: "1,00,000 IU" },
  { name: "Meftal-Forte", form: "Tablet", strength: "500 mg + 10 mg" },
  { name: "Ibugesic", form: "Tablet", strength: "400 mg" },
  { name: "Tramadol", form: "Injection", strength: "50 mg/ml" },
  { name: "Paracetamol IV", form: "Injection", strength: "1 g/100 ml" },

  /* ---- antibiotics & antimicrobials ---- */
  { name: "Augmentin", form: "Tablet", strength: "625 mg" },
  { name: "Augmentin", form: "Syrup", strength: "228 mg/5 ml" },
  { name: "Augmentin", form: "Suspension", strength: "457 mg/5 ml" },
  { name: "Augmentin", form: "Injection", strength: "1.2 g" },
  { name: "Clavam", form: "Tablet", strength: "625 mg" },
  { name: "Clavam", form: "Syrup", strength: "228 mg/5 ml" },
  { name: "Clavam", form: "Injection", strength: "1.2 g" },
  { name: "Moxikind-CV", form: "Tablet", strength: "625 mg" },
  { name: "Moxikind-CV", form: "Syrup", strength: "156.25 mg/5 ml" },
  { name: "Azithral", form: "Tablet", strength: "250 mg" },
  { name: "Azithral", form: "Tablet", strength: "500 mg" },
  { name: "Azithral", form: "Suspension", strength: "200 mg/5 ml" },
  { name: "Azithral", form: "Drops", strength: "100 mg/ml" },
  { name: "Azee", form: "Tablet", strength: "500 mg" },
  { name: "Azee", form: "Injection", strength: "500 mg" },
  { name: "Taxim-O", form: "Tablet", strength: "200 mg" },
  { name: "Taxim-O", form: "Suspension", strength: "50 mg/5 ml" },
  { name: "Zifi", form: "Tablet", strength: "200 mg" },
  { name: "Zifi", form: "Suspension", strength: "50 mg/5 ml" },
  { name: "Monocef", form: "Injection", strength: "1 g" },
  { name: "Ciplox", form: "Tablet", strength: "500 mg" },
  { name: "Ciplox-D", form: "Drops", strength: "0.3% eye/ear" },
  { name: "Zanocin", form: "Tablet", strength: "200 mg" },
  { name: "O2", form: "Tablet", strength: "200 mg + 500 mg" },
  { name: "Norflox-TZ", form: "Tablet", strength: "400 mg + 600 mg" },
  { name: "Metrogyl", form: "Tablet", strength: "400 mg" },
  { name: "Metrogyl", form: "Suspension", strength: "200 mg/5 ml" },
  { name: "Metrogyl", form: "Injection", strength: "500 mg/100 ml IV" },
  { name: "Tiniba", form: "Tablet", strength: "500 mg" },
  { name: "Doxt-SL", form: "Capsule", strength: "100 mg" },
  { name: "Claribid", form: "Tablet", strength: "250 mg" },
  { name: "Claribid", form: "Tablet", strength: "500 mg" },
  { name: "Roxid", form: "Tablet", strength: "150 mg" },
  { name: "Roxid", form: "Syrup", strength: "50 mg/5 ml" },
  { name: "Valcivir", form: "Tablet", strength: "500 mg" },
  { name: "Valcivir", form: "Tablet", strength: "1000 mg" },
  { name: "Nuforce", form: "Tablet", strength: "150 mg" },
  { name: "Novamox", form: "Capsule", strength: "500 mg" },
  { name: "Novamox", form: "Syrup", strength: "250 mg/5 ml" },
  { name: "Cefolac", form: "Tablet", strength: "200 mg" },
  { name: "Cefolac", form: "Suspension", strength: "50 mg/5 ml" },
  { name: "Althrocin", form: "Tablet", strength: "250 mg" },
  { name: "Althrocin", form: "Tablet", strength: "500 mg" },
  { name: "Minicycline", form: "Capsule", strength: "50 mg" },
  { name: "Minicycline", form: "Capsule", strength: "100 mg" },
  { name: "Gudcef", form: "Tablet", strength: "200 mg" },

  /* ---- allergy / cold / cough ---- */
  { name: "Okacet", form: "Tablet", strength: "10 mg" },
  { name: "Okacet", form: "Syrup", strength: "5 mg/5 ml" },
  { name: "Cetzine", form: "Tablet", strength: "10 mg" },
  { name: "Cetzine", form: "Syrup", strength: "5 mg/5 ml" },
  { name: "Avil", form: "Tablet", strength: "25 mg" },
  { name: "Avil", form: "Injection", strength: "22.75 mg/ml" },
  { name: "Allegra", form: "Tablet", strength: "120 mg" },
  { name: "Allegra", form: "Tablet", strength: "180 mg" },
  { name: "Montek-LC", form: "Tablet", strength: "10 mg + 5 mg" },
  { name: "Montek-LC", form: "Suspension", strength: "4 mg + 2.5 mg/5 ml" },
  { name: "Sinarest", form: "Tablet", strength: "500 mg + 2 mg + 10 mg" },
  { name: "Sinarest", form: "Syrup", strength: "AF paediatric" },
  { name: "Sinarest", form: "Drops", strength: "paediatric oral" },
  { name: "Benadryl", form: "Syrup", strength: "cough formula" },
  { name: "Corex DX", form: "Syrup", strength: "10 mg + 5 mg/5 ml" },
  { name: "Phensedyl", form: "Syrup", strength: "cough linctus" },
  { name: "Ascoril-LS", form: "Syrup", strength: "ambroxol + levosalbutamol" },
  { name: "Ambrodil-S", form: "Syrup", strength: "15 mg + 1 mg/5 ml" },
  { name: "Asthakind-DX", form: "Syrup", strength: "10 mg + 5 mg/5 ml" },
  { name: "Chericof", form: "Syrup", strength: "4 mg + 10 mg/5 ml" },
  { name: "Phenergan", form: "Syrup", strength: "5 mg/5 ml" },
  { name: "Zyncet", form: "Syrup", strength: "5 mg/5 ml" },
  { name: "Grilinctus", form: "Syrup", strength: "10 mg/5 ml" },
  { name: "Fexofast", form: "Tablet", strength: "120 mg" },
  { name: "Fexofast", form: "Tablet", strength: "180 mg" },
  { name: "Montair", form: "Tablet", strength: "10 mg" },
  { name: "Montair", form: "Tablet", strength: "4 mg chewable" },
  { name: "Telekast", form: "Tablet", strength: "10 mg" },

  /* ---- asthma / breathing ---- */
  { name: "Asthalin", form: "Inhaler", strength: "100 mcg/dose" },
  { name: "Asthalin", form: "Syrup", strength: "2 mg/5 ml" },
  { name: "Duolin", form: "Inhaler", strength: "100 mcg + 40 mcg" },
  { name: "Duolin", form: "Suspension", strength: "1.25 mg + 500 mcg respules" },
  { name: "Budecort", form: "Inhaler", strength: "100 mcg/dose" },
  { name: "Budecort", form: "Suspension", strength: "0.5 mg respules" },
  { name: "Foracort", form: "Inhaler", strength: "6 mcg + 100/200/400 mcg" },
  { name: "Seroflo", form: "Inhaler", strength: "50 mcg + 250 mcg" },
  { name: "Deriphyllin", form: "Tablet", strength: "retard 150 mg" },
  { name: "Deriphyllin", form: "Injection", strength: "253 mg ampoule" },
  { name: "Doxolin MTI", form: "Tablet", strength: "400 mg" },

  /* ---- stomach / acidity / vomiting / deworming ---- */
  { name: "Pan 40", form: "Tablet", strength: "40 mg" },
  { name: "Pan 40", form: "Injection", strength: "40 mg" },
  { name: "Pan-D", form: "Capsule", strength: "40 mg + 30 mg" },
  { name: "Sompraz", form: "Tablet", strength: "40 mg" },
  { name: "Sompraz", form: "Injection", strength: "40 mg" },
  { name: "Rablet", form: "Tablet", strength: "20 mg" },
  { name: "Rablet-D", form: "Capsule", strength: "20 mg + 30 mg" },
  { name: "Omez", form: "Capsule", strength: "20 mg" },
  { name: "Omez Insta", form: "Sachet", strength: "20 mg" },
  { name: "Digene", form: "Suspension", strength: "antacid gel, mint" },
  { name: "Gelusil-MPS", form: "Suspension", strength: "antacid gel" },
  { name: "Mucaine", form: "Suspension", strength: "gel 10 ml dose" },
  { name: "Emeset", form: "Tablet", strength: "4 mg" },
  { name: "Emeset", form: "Syrup", strength: "2 mg/5 ml" },
  { name: "Emeset", form: "Injection", strength: "2 mg/ml" },
  { name: "Vomikind", form: "Syrup", strength: "2 mg/5 ml" },
  { name: "Perinorm", form: "Tablet", strength: "10 mg" },
  { name: "Perinorm", form: "Injection", strength: "10 mg/2 ml" },
  { name: "Domstal", form: "Tablet", strength: "10 mg" },
  { name: "Domstal", form: "Suspension", strength: "1 mg/ml" },
  { name: "Cyclopam", form: "Tablet", strength: "10 mg + 500 mg" },
  { name: "Cyclopam", form: "Suspension", strength: "10 mg/5 ml" },
  { name: "Cyclopam", form: "Injection", strength: "20 mg/2 ml" },
  { name: "Buscopan", form: "Tablet", strength: "10 mg" },
  { name: "Buscopan", form: "Injection", strength: "20 mg/ml" },
  { name: "Drotin", form: "Tablet", strength: "40 mg" },
  { name: "Drotin", form: "Injection", strength: "20 mg/ml" },
  { name: "Normaxin", form: "Tablet", strength: "2.5 mg + 10 mg + 5 mg" },
  { name: "Lactihep", form: "Syrup", strength: "10 g/15 ml" },
  { name: "Cremaffin", form: "Syrup", strength: "3.75 ml + 11.25 mg/5 ml" },
  { name: "Econorm", form: "Sachet", strength: "250 mg" },
  { name: "Lopamide", form: "Tablet", strength: "2 mg" },
  { name: "Electral", form: "Sachet", strength: "21.8 g (ORS)" },
  { name: "Enteroglycin", form: "Sachet", strength: "ORS + zinc" },
  { name: "Zentel", form: "Tablet", strength: "400 mg" },
  { name: "Zentel", form: "Suspension", strength: "200 mg/5 ml" },
  { name: "Bandy-Plus", form: "Tablet", strength: "400 mg + 6 mg" },
  { name: "Dicaris", form: "Tablet", strength: "50 mg" },
  { name: "Dicaris", form: "Tablet", strength: "150 mg" },
  { name: "Liv 52", form: "Tablet", strength: "Himalaya" },
  { name: "Liv 52", form: "Syrup", strength: "Himalaya" },
  { name: "Gravol", form: "Tablet", strength: "50 mg" },
  { name: "Vomistop", form: "Tablet", strength: "10 mg" },
  { name: "Vomistop", form: "Syrup", strength: "1 mg/ml" },
  { name: "Ondem-MD", form: "Tablet", strength: "4 mg mouth-dissolving" },
  { name: "ENO", form: "Sachet", strength: "5 g lemon" },
  { name: "Digene", form: "Tablet", strength: "mint chewable" },
  { name: "Glucon-D", form: "Sachet", strength: "100 g" },
  { name: "Rabemac", form: "Tablet", strength: "20 mg" },
  { name: "Pantocid", form: "Tablet", strength: "40 mg" },
  { name: "Pantocid", form: "Injection", strength: "40 mg" },

  /* ---- diabetes / thyroid ---- */
  { name: "Glycomet", form: "Tablet", strength: "500 mg" },
  { name: "Glycomet", form: "Tablet", strength: "500 mg SR" },
  { name: "Glycomet", form: "Tablet", strength: "850 mg" },
  { name: "Amaryl", form: "Tablet", strength: "1 mg" },
  { name: "Amaryl", form: "Tablet", strength: "2 mg" },
  { name: "Amaryl", form: "Tablet", strength: "3 mg" },
  { name: "Janumet", form: "Tablet", strength: "50/500 mg" },
  { name: "Janumet", form: "Tablet", strength: "50/1000 mg" },
  { name: "Glucophage", form: "Tablet", strength: "500 mg" },
  { name: "Galvus-Met", form: "Tablet", strength: "50/500 mg" },
  { name: "Trajenta", form: "Tablet", strength: "5 mg" },
  { name: "Human Mixtard", form: "Injection", strength: "40 IU/ml" },
  { name: "Insugen-R", form: "Injection", strength: "40 IU/ml" },
  { name: "Lantus", form: "Injection", strength: "100 IU/ml" },
  { name: "Thyronorm", form: "Tablet", strength: "25 mcg" },
  { name: "Thyronorm", form: "Tablet", strength: "50 mcg" },
  { name: "Thyronorm", form: "Tablet", strength: "75 mcg" },
  { name: "Thyronorm", form: "Tablet", strength: "100 mcg" },

  /* ---- heart / BP / lipids / blood thinners ---- */
  { name: "Telma", form: "Tablet", strength: "20 mg" },
  { name: "Telma", form: "Tablet", strength: "40 mg" },
  { name: "Telma", form: "Tablet", strength: "80 mg" },
  { name: "Amlong", form: "Tablet", strength: "2.5 mg" },
  { name: "Amlong", form: "Tablet", strength: "5 mg" },
  { name: "Amlong", form: "Tablet", strength: "10 mg" },
  { name: "Losar", form: "Tablet", strength: "25 mg" },
  { name: "Losar", form: "Tablet", strength: "50 mg" },
  { name: "Cardace", form: "Tablet", strength: "2.5 mg" },
  { name: "Cardace", form: "Tablet", strength: "5 mg" },
  { name: "Cardace", form: "Tablet", strength: "10 mg" },
  { name: "Betacap TR", form: "Capsule", strength: "40 mg" },
  { name: "Ecosprin AV", form: "Capsule", strength: "75/20 mg" },
  { name: "Ecosprin", form: "Tablet", strength: "75 mg" },
  { name: "Ecosprin", form: "Tablet", strength: "150 mg" },
  { name: "Clopilet", form: "Tablet", strength: "75 mg" },
  { name: "Clopivas", form: "Tablet", strength: "75 mg" },
  { name: "Atorva", form: "Tablet", strength: "10 mg" },
  { name: "Atorva", form: "Tablet", strength: "20 mg" },
  { name: "Atorva", form: "Tablet", strength: "40 mg" },
  { name: "Rozavel", form: "Tablet", strength: "10 mg" },
  { name: "Storvas", form: "Tablet", strength: "10 mg" },
  { name: "Inderal", form: "Tablet", strength: "10 mg" },
  { name: "Inderal", form: "Tablet", strength: "40 mg" },
  { name: "Sorbitrate", form: "Tablet", strength: "5 mg sublingual" },
  { name: "Sorbitrate", form: "Tablet", strength: "10 mg" },
  { name: "Monotrate OD", form: "Tablet", strength: "50 mg" },

  /* ---- steroids ---- */
  { name: "Betnesol", form: "Tablet", strength: "0.5 mg" },
  { name: "Betnesol", form: "Injection", strength: "4 mg/ml" },
  { name: "Betnesol", form: "Drops", strength: "eye/ear 0.1%" },
  { name: "Wysolone", form: "Tablet", strength: "5 mg" },
  { name: "Wysolone", form: "Tablet", strength: "10 mg" },
  { name: "Wysolone", form: "Tablet", strength: "20 mg" },
  { name: "Omnacortil", form: "Tablet", strength: "5 mg" },
  { name: "Omnacortil", form: "Tablet", strength: "10 mg" },
  { name: "Omnacortil", form: "Tablet", strength: "20 mg" },
  { name: "Defcort", form: "Tablet", strength: "6 mg" },
  { name: "Defcort", form: "Tablet", strength: "30 mg" },
  { name: "Medrol", form: "Tablet", strength: "4 mg" },
  { name: "Medrol", form: "Tablet", strength: "8 mg" },
  { name: "Dexona", form: "Injection", strength: "4 mg/ml" },
  { name: "Dexona", form: "Tablet", strength: "0.5 mg" },
  { name: "Hydrocortisone", form: "Injection", strength: "100 mg" },

  /* ---- nerve / brain / sleep ---- */
  { name: "Levipil", form: "Tablet", strength: "500 mg" },
  { name: "Levipil", form: "Tablet", strength: "750 mg" },
  { name: "Eptoin", form: "Tablet", strength: "100 mg" },
  { name: "Eptoin", form: "Injection", strength: "100 mg/2 ml" },
  { name: "Alzil", form: "Tablet", strength: "5 mg" },
  { name: "Alzil", form: "Tablet", strength: "10 mg" },
  { name: "Nexito", form: "Tablet", strength: "5 mg" },
  { name: "Nexito", form: "Tablet", strength: "10 mg" },
  { name: "Zolfresh", form: "Tablet", strength: "5 mg" },
  { name: "Zolfresh", form: "Tablet", strength: "10 mg" },
  { name: "Pregastar-M", form: "Capsule", strength: "75 mg + 1500 mcg" },
  { name: "Nervz-G", form: "Tablet", strength: "300 mg + 500 mcg" },
  { name: "Methylcobal", form: "Tablet", strength: "1500 mcg" },
  { name: "Serenace", form: "Injection", strength: "5 mg/ml" },
  { name: "Zyloric", form: "Tablet", strength: "100 mg" },
  { name: "Zyloric", form: "Tablet", strength: "300 mg" },
  { name: "Febucip", form: "Tablet", strength: "40 mg" },
  { name: "Febucip", form: "Tablet", strength: "80 mg" },

  /* ---- women / gynae ---- */
  { name: "Primolut-N", form: "Tablet", strength: "5 mg" },
  { name: "Duphaston", form: "Tablet", strength: "10 mg" },
  { name: "Deviry", form: "Tablet", strength: "10 mg" },
  { name: "Proluton", form: "Injection", strength: "250 mg" },
  { name: "Proluton", form: "Injection", strength: "500 mg" },
  { name: "I-Pill", form: "Tablet", strength: "1.5 mg" },
  { name: "Saheli", form: "Tablet", strength: "30 mg" },

  /* ---- vitamins / iron / calcium ---- */
  { name: "Zincovit", form: "Tablet", strength: "multivitamin" },
  { name: "Zincovit", form: "Syrup", strength: "multivitamin" },
  { name: "Zincovit", form: "Drops", strength: "paediatric" },
  { name: "Becosules", form: "Capsule", strength: "B-complex" },
  { name: "Neurobion", form: "Tablet", strength: "Forte" },
  { name: "Neurobion", form: "Injection", strength: "3 ml" },
  { name: "Shelcal", form: "Tablet", strength: "500 mg calcium" },
  { name: "Shelcal", form: "Suspension", strength: "250 mg/5 ml" },
  { name: "Calcimax Forte", form: "Tablet", strength: "500 mg + D3" },
  { name: "Calcimax P", form: "Syrup", strength: "paediatric" },
  { name: "Evion", form: "Capsule", strength: "400 mg" },
  { name: "Evion", form: "Capsule", strength: "600 mg" },
  { name: "Limcee", form: "Tablet", strength: "500 mg chewable" },
  { name: "Orofer XT", form: "Tablet", strength: "iron + folic acid" },
  { name: "Feronia-XT", form: "Syrup", strength: "iron 30 mg/5 ml" },
  { name: "Arachitol", form: "Injection", strength: "6,00,000 IU" },
  { name: "Surbex XT", form: "Tablet", strength: "multivitamin" },
  { name: "Supradyn", form: "Tablet", strength: "daily multivitamin" },
  { name: "Caldikind Plus", form: "Tablet", strength: "D3 chewable" },
  { name: "Polybion L", form: "Syrup", strength: "B-complex elixir" },
  { name: "Beplex Forte", form: "Tablet", strength: "B-complex" },
  { name: "Beplex Forte", form: "Injection", strength: "2 ml" },

  /* ---- eye / ear / nose ---- */
  { name: "Refresh Tears", form: "Drops", strength: "0.5%/0.3%" },
  { name: "Moxicip", form: "Drops", strength: "0.5% eye" },
  { name: "Toba", form: "Drops", strength: "0.3% eye" },
  { name: "Itone", form: "Drops", strength: "herbal eye" },
  { name: "Otiflox", form: "Drops", strength: "ear 0.3%" },
  { name: "Nasivion", form: "Drops", strength: "0.01% paediatric" },
  { name: "Otrivin", form: "Drops", strength: "0.05% paediatric" },
  { name: "Otrivin", form: "Drops", strength: "0.1% adult" },
  { name: "Colicaid", form: "Drops", strength: "40 mg/ml simethicone" },

  /* ---- skin / antiseptic ---- */
  { name: "Betadine", form: "Ointment / Cream", strength: "5%" },
  { name: "Soframycin", form: "Ointment / Cream", strength: "1%" },
  { name: "Candid-B", form: "Ointment / Cream", strength: "1% + 0.05%" },
  { name: "Clop-S", form: "Ointment / Cream", strength: "0.05% + 3%" },
  { name: "Medisalic", form: "Ointment / Cream", strength: "0.05% + 3%" },
  { name: "Tenovate", form: "Ointment / Cream", strength: "0.05%" },
  { name: "Quadriderm", form: "Ointment / Cream", strength: "4-way" },
  { name: "Ring-Guard", form: "Ointment / Cream", strength: "miconazole 2%" },
  { name: "Fusiwal", form: "Ointment / Cream", strength: "2%" },

  /* ---- hospital injectables ---- */
  { name: "Amikacin", form: "Injection", strength: "500 mg/2 ml" },
  { name: "Gentamicin", form: "Injection", strength: "80 mg/2 ml" },
  { name: "Lasix", form: "Tablet", strength: "40 mg" },
  { name: "Lasix", form: "Injection", strength: "20 mg/2 ml" },
  { name: "Tranexa", form: "Injection", strength: "500 mg/5 ml" },
  { name: "Trapic", form: "Tablet", strength: "500 mg" },
  { name: "Trapic", form: "Injection", strength: "500 mg/5 ml" },
  { name: "Calcium Gluconate", form: "Injection", strength: "10% 10 ml" },
  { name: "Adrenaline", form: "Injection", strength: "1 mg/ml" },
];
