/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as HandoverRouteImport } from './routes/handover'
import { Route as IpdRouteImport } from './routes/ipd'
import { Route as LabOrdersRouteImport } from './routes/lab-orders'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as RadiologyRouteImport } from './routes/radiology'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as SyncRouteImport } from './routes/sync'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverRoute = HandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => rootRouteImport,
} as any)
const IpdRoute = IpdRouteImport.update({
  id: '/ipd',
  path: '/ipd',
  getParentRoute: () => rootRouteImport,
} as any)
const LabOrdersRoute = LabOrdersRouteImport.update({
  id: '/lab-orders',
  path: '/lab-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiologyRoute = RadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncRoute = SyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/expenses': typeof ExpensesRoute
  '/handover': typeof HandoverRoute
  '/ipd': typeof IpdRoute
  '/lab-orders': typeof LabOrdersRoute
  '/laboratory': typeof LaboratoryRoute
  '/payroll': typeof PayrollRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/queue': typeof QueueRoute
  '/radiology': typeof RadiologyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/sync': typeof SyncRoute
  '/visits': typeof VisitsRoute
  '/workspace': typeof WorkspaceRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/expenses': typeof ExpensesRoute
  '/handover': typeof HandoverRoute
  '/ipd': typeof IpdRoute
  '/lab-orders': typeof LabOrdersRoute
  '/laboratory': typeof LaboratoryRoute
  '/payroll': typeof PayrollRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/queue': typeof QueueRoute
  '/radiology': typeof RadiologyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/sync': typeof SyncRoute
  '/visits': typeof VisitsRoute
  '/workspace': typeof WorkspaceRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/audit': typeof AuditRoute
  '/billing': typeof BillingRoute
  '/expenses': typeof ExpensesRoute
  '/handover': typeof HandoverRoute
  '/ipd': typeof IpdRoute
  '/lab-orders': typeof LabOrdersRoute
  '/laboratory': typeof LaboratoryRoute
  '/payroll': typeof PayrollRoute
  '/pharmacy': typeof PharmacyRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/queue': typeof QueueRoute
  '/radiology': typeof RadiologyRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/sync': typeof SyncRoute
  '/visits': typeof VisitsRoute
  '/workspace': typeof WorkspaceRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/audit'
    | '/billing'
    | '/expenses'
    | '/handover'
    | '/ipd'
    | '/lab-orders'
    | '/laboratory'
    | '/payroll'
    | '/pharmacy'
    | '/prescriptions'
    | '/queue'
    | '/radiology'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/sync'
    | '/visits'
    | '/workspace'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/audit'
    | '/billing'
    | '/expenses'
    | '/handover'
    | '/ipd'
    | '/lab-orders'
    | '/laboratory'
    | '/payroll'
    | '/pharmacy'
    | '/prescriptions'
    | '/queue'
    | '/radiology'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/sync'
    | '/visits'
    | '/workspace'
    | '/patients/$patientId'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/audit'
    | '/billing'
    | '/expenses'
    | '/handover'
    | '/ipd'
    | '/lab-orders'
    | '/laboratory'
    | '/payroll'
    | '/pharmacy'
    | '/prescriptions'
    | '/queue'
    | '/radiology'
    | '/reports'
    | '/settings'
    | '/staff'
    | '/sync'
    | '/visits'
    | '/workspace'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuditRoute: typeof AuditRoute
  BillingRoute: typeof BillingRoute
  ExpensesRoute: typeof ExpensesRoute
  HandoverRoute: typeof HandoverRoute
  IpdRoute: typeof IpdRoute
  LabOrdersRoute: typeof LabOrdersRoute
  LaboratoryRoute: typeof LaboratoryRoute
  PayrollRoute: typeof PayrollRoute
  PharmacyRoute: typeof PharmacyRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  QueueRoute: typeof QueueRoute
  RadiologyRoute: typeof RadiologyRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  SyncRoute: typeof SyncRoute
  VisitsRoute: typeof VisitsRoute
  WorkspaceRoute: typeof WorkspaceRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover': {
      id: '/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof HandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipd': {
      id: '/ipd'
      path: '/ipd'
      fullPath: '/ipd'
      preLoaderRoute: typeof IpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-orders': {
      id: '/lab-orders'
      path: '/lab-orders'
      fullPath: '/lab-orders'
      preLoaderRoute: typeof LabOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radiology': {
      id: '/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof RadiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sync': {
      id: '/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuditRoute: AuditRoute,
  BillingRoute: BillingRoute,
  ExpensesRoute: ExpensesRoute,
  HandoverRoute: HandoverRoute,
  IpdRoute: IpdRoute,
  LabOrdersRoute: LabOrdersRoute,
  LaboratoryRoute: LaboratoryRoute,
  PayrollRoute: PayrollRoute,
  PharmacyRoute: PharmacyRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  QueueRoute: QueueRoute,
  RadiologyRoute: RadiologyRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  SyncRoute: SyncRoute,
  VisitsRoute: VisitsRoute,
  WorkspaceRoute: WorkspaceRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
