/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as LaboratoryRouteImport } from './routes/laboratory'
import { Route as PharmacyRouteImport } from './routes/pharmacy'
import { Route as RadiologyRouteImport } from './routes/radiology'
import { Route as VisitsRouteImport } from './routes/visits'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const LaboratoryRoute = LaboratoryRouteImport.update({
  id: '/laboratory',
  path: '/laboratory',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyRoute = PharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RadiologyRoute = RadiologyRouteImport.update({
  id: '/radiology',
  path: '/radiology',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitsRoute = VisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/laboratory': typeof LaboratoryRoute
  '/pharmacy': typeof PharmacyRoute
  '/radiology': typeof RadiologyRoute
  '/visits': typeof VisitsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/laboratory': typeof LaboratoryRoute
  '/pharmacy': typeof PharmacyRoute
  '/radiology': typeof RadiologyRoute
  '/visits': typeof VisitsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients': typeof PatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/laboratory': typeof LaboratoryRoute
  '/pharmacy': typeof PharmacyRoute
  '/radiology': typeof RadiologyRoute
  '/visits': typeof VisitsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/': typeof PatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/laboratory'
    | '/pharmacy'
    | '/radiology'
    | '/visits'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/laboratory'
    | '/pharmacy'
    | '/radiology'
    | '/visits'
    | '/patients/$patientId'
    | '/patients'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/laboratory'
    | '/pharmacy'
    | '/radiology'
    | '/visits'
    | '/patients/$patientId'
    | '/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  LaboratoryRoute: typeof LaboratoryRoute
  PharmacyRoute: typeof PharmacyRoute
  RadiologyRoute: typeof RadiologyRoute
  VisitsRoute: typeof VisitsRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laboratory': {
      id: '/laboratory'
      path: '/laboratory'
      fullPath: '/laboratory'
      preLoaderRoute: typeof LaboratoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy': {
      id: '/pharmacy'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof PharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radiology': {
      id: '/radiology'
      path: '/radiology'
      fullPath: '/radiology'
      preLoaderRoute: typeof RadiologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visits': {
      id: '/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof VisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  LaboratoryRoute: LaboratoryRoute,
  PharmacyRoute: PharmacyRoute,
  RadiologyRoute: RadiologyRoute,
  VisitsRoute: VisitsRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
